_extends: openplatform-kubewarden-policies:.github/release-drafter.yml
name-template: "harvester-restricted-network/v$RESOLVED_VERSION"
tag-template: "harvester-restricted-network/v$RESOLVED_VERSION"
tag-prefix: harvester-restricted-network/v
include-paths:
  - "policies/harvester-restricted-network/"
