_extends: openplatform-kubewarden-policies:.github/release-drafter.yml
name-template: "istio-gateway/v$RESOLVED_VERSION"
tag-template: "istio-gateway/v$RESOLVED_VERSION"
tag-prefix: istio-gateway/v
include-paths:
  - "policies/istio-gateway/"
