name: 'Policy Matrix'
description: 'Retrieves the changed policies'
outputs:
  policy_working_dirs:
    description: 'The directories of the changed policies'
    value: ${{ steps.calculate-policy-dirs.outputs.policy_working_dirs }}
runs:
  using: 'composite'
  steps:
    - name: calculate which policies need a CI job
      id: calculate-policy-dirs
      shell: bash
      run: |
        git remote -v

        policies_working_dirs=($(find policies -maxdepth 2 -name Makefile -exec dirname '{}' \;))
        if [ "${{github.event_name}}" == "pull_request" ]; then
          # list only changes of files in `policies/`:
          git_files="$(git diff --no-color --find-renames --find-copies --name-only origin/${{ github.base_ref }} ${{ github.sha }} -- policies)"

          # build policy_working_dirs:
          policies_working_dirs=($(echo "$git_files" | cut -d/ -f1,2 ))
        fi

        declare -p policies_working_dirs # for debug
        policy_working_dirs=$(jq --compact-output --null-input '$ARGS.positional | map(select(. != "policies/Cargo.lock" and . != "policies/Cargo.toml" and . != "policies/go.mod" and . != "policies/go.sum")) | unique' --args -- "${policies_working_dirs[@]}")
        echo "policy_working_dirs=$policy_working_dirs"
        echo "policy_working_dirs=$policy_working_dirs" >> $GITHUB_OUTPUT
